spring.application.name=wedding-invitation
server.port=${PORT:8080}

# Aiven MySQL Cloud Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-2b7ddcb6-adi2002rawat-8e10.k.aivencloud.com:15662/defaultdb?sslMode=REQUIRED&allowPublicKeyRetrieval=true&useSSL=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Hibernate / JPA configuration
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Admin Authentication
wedding.admin.password=P@ssw0rd

# Static & Web Configuration
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.web.resources.static-locations=classpath:/static/
